### ISSUE TITLE
Encountering the issue when run this code "CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only --grad_normal"

### ISSUE THREAD

**Issue by WuyiWong** [vLAR-group/RayDF#6]
hi, when I follow you tip to evaluate the ray-surface distance network through this code "CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only --grad_normal". I encounter this error:
/********************************/
Traceback (most recent call last):
  File "run_mv.py", line 405, in <module>
    evaluate(args)
  File "run_mv.py", line 331, in evaluate
    depth = convert_d(vis_results['dist_abs'].squeeze().cpu().numpy(), dataloader.scene_info, out='dep')
KeyError: 'dist_abs'
/********************************/

why could this thing happen?
![1700839361127](https://github.com/vLAR-group/RayDF/assets/54266533/7c2af96b-1a5b-4ac8-98a7-2f3ff515b8bf)

**Comment by zhuomanliu** [comment]
vis_results['dist_abs'] is stored when using `--denoise` in the previous code. The code has been updated to fix this issue when using only `--grad_normal`.

**Comment by WuyiWong** [comment]
thanks for your answer. But it seems that there is another issue I've encountered when I run this code "CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only" to evaluate the distance network. 

[train] ADE=1.1995 CD=955.4302 CD_median=827.3363 PSNR=nan SSIM=nan LPIPS=nan
[test] ADE=1.1883 CD=949.7096 CD_median=835.1572 PSNR=nan SSIM=nan LPIPS=nan

why are the the values of CD, CD_median, PSNR, SSIM and LPIPS so strange,  I wonder if it has anything to do with "scene lego"?

**Comment by zhuomanliu** [comment]
> thanks for your answer. But it seems that there is another issue I've encountered when I run this code "CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only" to evaluate the distance network.
> 
> [train] ADE=1.1995 CD=955.4302 CD_median=827.3363 PSNR=nan SSIM=nan LPIPS=nan [test] ADE=1.1883 CD=949.7096 CD_median=835.1572 PSNR=nan SSIM=nan LPIPS=nan
> 
> why are the the values of CD, CD_median, PSNR, SSIM and LPIPS so strange, I wonder if it has anything to do with "scene lego"?

Have you loaded the pre-trained model during evaluation? The print log should be like this: 'Loading ckpt from: logs/multiview/...'
![image](https://github.com/vLAR-group/RayDF/assets/20896246/f7cdaaa8-7ce6-42fe-93f3-58fea2ddc81b)

**Comment by WuyiWong** [comment]
Hi,

Thanks for your patience.
It seems like the pretrained model loaded failed in my code, as shown below.
<img width="1130" alt="image" src="https://github.com/vLAR-group/RayDF/assets/54266533/c1a56854-da0e-4342-9929-daa66c57d8df">

But I followed you evaluation steps and downloaded the checkpoints from the link you've shared. Is my step wrong?

<img width="274" alt="image" src="https://github.com/vLAR-group/RayDF/assets/54266533/2bf12837-f790-4467-b543-f690d235371f">

<img width="781" alt="image" src="https://github.com/vLAR-group/RayDF/assets/54266533/a8dda76e-e822-4a41-88b0-32dd386f8522">

**Comment by zhuomanliu** [comment]
> Hi,
> 
> Thanks for your patience. It seems like the pretrained model loaded failed in my code, as shown below. <img alt="image" width="1130" src="https://private-user-images.githubusercontent.com/54266533/285562572-c1a56854-da0e-4342-9929-daa66c57d8df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODM2NDAsIm5iZiI6MTcwMDg4MzM0MCwicGF0aCI6Ii81NDI2NjUzMy8yODU1NjI1NzItYzFhNTY4NTQtZGEwZS00MzQyLTk5MjktZGFhNjZjNTdkOGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAzMzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MmY1ZTFhYmYyZTM2NTk0ZjUwYTUzZGE2NzM2NTM5YjNmZGJiZDY4ZmRkY2UxOGQzNzI4ODU4MDNlODgwMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b67MijueeRB4SmL7Z3kYDqa-B75FdvbbBtj6MU22PPI">
> 
> But I followed you evaluation steps and downloaded the checkpoints from the link you've shared. Is my step wrong?
> 
> <img alt="image" width="274" src="https://private-user-images.githubusercontent.com/54266533/285562781-2bf12837-f790-4467-b543-f690d235371f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODM2NDAsIm5iZiI6MTcwMDg4MzM0MCwicGF0aCI6Ii81NDI2NjUzMy8yODU1NjI3ODEtMmJmMTI4MzctZjc5MC00NDY3LWI1NDMtZjY5MGQyMzUzNzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAzMzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDIwYmExNGE1ODY2MTUyYWU4YjA4MDRjYTJjZTllOWQ4MDYwODFkMDc1MTY3NjFmMWZiYjhkZDRkZjk0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eSx_F84bKJr6b4OnlBp5V79YaMbvx_qpAM_mGdAKSBg"> <img alt="image" width="781" src="https://private-user-images.githubusercontent.com/54266533/285562844-a8dda76e-e822-4a41-88b0-32dd386f8522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4ODM2NDAsIm5iZiI6MTcwMDg4MzM0MCwicGF0aCI6Ii81NDI2NjUzMy8yODU1NjI4NDQtYThkZGE3NmUtZTgyMi00YTQxLTg4YjAtMzJkZDM4NmY4NTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDAzMzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YTIxNzFlYmUyZDMyNjA1MGU0MzUxNmFkOGE1MDc4MjU2YTYwNjJlOWM2Y2U1MWRjN2QxOTBkNGU5YTlmOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fyGrdiOahqyC6xdgQqWx_h376cIpbK6rjW540BQ0kMA">

How about the folder name you downloaded? It should be 'blender-lego_mv20d13w1024rgb0w1.0_lr1e-05bs8192iters80k' for Lego (geometry only). To be more specific, you can run this: "CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only --grad_normal --expname mv20d13w1024rgb0w1.0_lr1e-05bs8192iters80k" to make sure the loaded folder name is correct.

**Comment by WuyiWong** [comment]
Hi, I've found the issue of my implementation. During adjustment, I've finally loaded the pre-trained model during evaluation. Thank your so much. The print log be like this: 'Loading ckpt from: logs/multiview/...'
<img width="1074" alt="image" src="https://github.com/vLAR-group/RayDF/assets/54266533/9c9b583e-2e62-4722-9317-33d6e1e504d2">


But, there are still some issue in it. the value of PSNR and SSIM is really weird, is it normal? as shown below.
<img width="689" alt="image" src="https://github.com/vLAR-group/RayDF/assets/54266533/53540505-e26d-4479-b6ca-dae7c6d5dcf1">

**Comment by zhuomanliu** [comment]
> Hi, I've found the issue of my implementation. During adjustment, I've finally loaded the pre-trained model during evaluation. Thank your so much. The print log be like this: 'Loading ckpt from: logs/multiview/...' <img alt="image" width="1074" src="https://private-user-images.githubusercontent.com/54266533/285576968-9c9b583e-2e62-4722-9317-33d6e1e504d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDUyMjEsIm5iZiI6MTcwMDkwNDkyMSwicGF0aCI6Ii81NDI2NjUzMy8yODU1NzY5NjgtOWM5YjU4M2UtMmU2Mi00NzIyLTkzMTctMzNkNmUxZTUwNGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA5MzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzY2RlN2IyNzNhNWY5MWQ1OGFkNGY0YWZmYjkzNTYyMTQ2YWU5NTc0YWMxYjlkNzE5ZjEzOTA0MTFiNGVkMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ftXnm5VhGz1aVfVZrcHxDSf6875bOPpXTFG3ml9b-Lk">
> 
> But, there are still some issue in it. the value of PSNR and SSIM is really weird, is it normal? as shown below. <img alt="image" width="689" src="https://private-user-images.githubusercontent.com/54266533/285577019-53540505-e26d-4479-b6ca-dae7c6d5dcf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDUyMjEsIm5iZiI6MTcwMDkwNDkyMSwicGF0aCI6Ii81NDI2NjUzMy8yODU1NzcwMTktNTM1NDA1MDUtZTI2ZC00NDc5LWI2Y2EtZGFlN2M2ZDVkY2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA5MzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1M2ZlMGJjY2MyODUzOGExOGQ5MWQwMmVlMzM4YjZlM2M4NzM5MjRjYWU0NDhjODlhYmY2OWZiNmUxNWFjNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0IJhtJIwFo34SX3YzKpJP6bvsnkl76tRD5eEK4Wt6yQ">

It is because this is the geometry-only mode (experiment Group 1 in the paper). 
For geometry+radiance mode (experiment Group 2 in the paper), adding `--rgb_layer 2` is required, and then the code will load the checkpoint from the folder "scannet-scene0004_00_mv20d13w1024**rgb2**w1.0_lr1e-05bs8192iters80k".

**Comment by WuyiWong** [comment]
I see, thank you again for your patient explanation. 

Best regards.
